spring.application.name=SpringBootJDBC


# spring.datasource.url=jdbc:mysql://localhost:3306/alien?useSSL=false&allowPublicKeyRetrieval=true
# spring.datasource.username=root
# spring.datasource.password=#Ss9572716927
